Improve user config migration implementation
LiskHQ/lisk-migrator pull request #111
Opened 2023-05-23 15:17 UTC by nagdahimanshu

### What was the problem?

This PR resolves #81 

### How was it solved?

- [ ] The existing code implementation is refactored
- [ ] All possible entries from Lisk Core v3 config are migrated to Lisk Core v4 compatible config 
- [ ] Every migrated property is logged 
- [ ] Tests are up-to-date

### How was it tested?
Local

2023-05-25 13:30 UTC, sameersubudhi requested changes

2023-05-25 13:30 UTC, sameersubudhi commented on src/index.ts
> +					);
```suggestion
					const isUserConfirmed = await cli.confirm(`
						Start Lisk Core with the following configuration? [yes/no] \n
						${util.inspect(finalConfigCorev4, false, 3)}
					`);
```

2023-05-26 07:54 UTC, sameersubudhi commented on src/utils/config.ts
> +	if (!existsSync(outputPath)) {
Clarified offline!

2023-05-26 08:29 UTC, nagdahimanshu commented on src/types.ts
>  export interface NetworkConfig {
I checked and some are not exported from the SDK.

2023-05-30 09:10 UTC, nagdahimanshu commented on src/constants.ts
> +export const DEFAULT_VERSION = '0.1.0';
I confirmed with SDK and default version is `0.1.0`

2023-05-30 09:16 UTC, sameersubudhi approved these changes

2023-05-30 16:45 UTC, vardan10 approved these changes

2023-05-30 16:46 UTC, merged