Optimize migrator implementation #2
LiskHQ/lisk-migrator pull request #118
Opened 2023-06-15 15:02 UTC by nagdahimanshu

### What was the problem?

This PR resolves #110 

### How was it solved?

- [ ] Iterate over the accounts only once and process the genesisAssets for each module individually
- [ ] Iterate over the legacyAccounts only once (Optional)
- [ ] Ensure that the genesis blocks created before and after the change result in same hash/blockID
- [ ] The migration times should've reduced

### How was it tested?
Local 
- [ ] testnet
- [ ] mainnet

2023-06-16 14:00 UTC, sergeyshemyakov commented on src/assets/auth.ts
> +export const addAuthModuleEntry = async (
Not an error, just a small inconsistency. I think you sort all the other entries in `CreateAsset` and then pass already sorted data to `add...ModuleEntry`, only for Auth module you pass unsorted data and sort in `addAuthModuleEntry`. 
Maybe it makes sense to move the sorting logic into `createAsset.ts`.

2023-06-19 07:01 UTC, sameersubudhi requested changes

2023-06-19 07:01 UTC, sameersubudhi commented on src/createAsset.ts
> +			.sort((a, b) => a.address.compare(b.address))
Use a pre-defined comparator instead.

2023-06-19 14:22 UTC, sameersubudhi approved these changes
LGTM 👍

2023-06-19 14:22 UTC, merged