Update migrator to read the node snapshot
LiskHQ/lisk-migrator pull request #133
Opened 2023-08-07 11:50 UTC by nagdahimanshu

### What was the problem?

This PR resolves #131 

### How was it solved?

- [ ] Lisk Migrator ensures that the connected node version is 3.0.5 or above
- [ ] Remove support for min-compatible-version, snapshot-path and use-existing-snapshot, if min-compatible-version is forced to 3.0.5 in the application
- [ ] Lisk Migrator validates from the node:info (Lisk Core v3) if the backup.height matches the user specified snapshot_height
- [ ] Once the snapshot-height is finalized, the migrator now reads the backup (~/.lisk/lisk-core/data/backup by default or <lisk-core-v3-data-path>/data/backup) to start the migration process
- [ ] Temporarily set --ignore-engines when installing dependencies on the CI

### How was it tested?
Local against `testnet`

2023-08-15 15:06 UTC, sameersubudhi requested changes

2023-08-15 15:06 UTC, sameersubudhi commented on src/index.ts
> +			cli.action.stop('Snapshot Height matches backup height');
```suggestion
			cli.action.stop('Snapshot height matches backup height');
```

2023-08-16 07:47 UTC, nagdahimanshu commented on src/assets/pos.ts
> +export const formatInt = (num: number | bigint): string => {
Informed to expose the method and added TODO for this.

2023-08-16 07:51 UTC, sameersubudhi approved these changes

2023-08-16 07:51 UTC, sameersubudhi commented on src/index.ts
> +					`Lisk Migrator utility is not compatible for lisk-core version ${liskCoreVersion.version}. Compatible versions range is: ${MIN_SUPPORTED_LISK_CORE_VERSION}.`,
```suggestion
					`Lisk Migrator utility is not compatible for lisk-core version ${liskCoreVersion.version}. The minimum compatible version is: ${MIN_SUPPORTED_LISK_CORE_VERSION}.`,
```

2023-08-16 09:20 UTC, merged