Fix genesis block creation logic
LiskHQ/lisk-migrator pull request #148
Opened 2023-09-04 17:25 UTC by nagdahimanshu

### What was the problem?

This PR resolves #147 

### How was it solved?
- [ ] Fix genesis block creation logic to create genesis block with `lisk-core` instance
- [ ] Node should start with the genesis block created

### How was it tested?
Locally against `testnet`

2023-09-05 11:12 UTC, sameersubudhi requested changes
Please address the following and the remaining changes discussed offline.

2023-09-05 11:12 UTC, sameersubudhi commented on src/utils/genesis_block.ts
> +	await execAsync(genesisBlockCreateCommand);
```suggestion
	const height = blockAtSnapshotHeight.header.height + 1;
	const timestamp = blockAtSnapshotHeight.header.timestamp + snapshotTimeGap;
	const previousBlockID = blockAtSnapshotHeight.header.id.toString('hex');

	const genesisBlockCreateCommand = `lisk-core genesis-block:create --network ${network} --config=${configFilepath} --output=${outputPath} --assets-file=${outputPath}/genesis_assets.json --height=${height} --previous-block-id=${previousBlockID} --timestamp=${timestamp}`;

	await execAsync(genesisBlockCreateCommand);
```

2023-09-05 11:12 UTC, sameersubudhi commented on src/utils/genesis_block.ts
> +	output: string,
```suggestion
	network: string,
	configFilepath: string,
	outputPath: string,
```

2023-09-05 11:37 UTC, sameersubudhi approved these changes

2023-09-07 11:25 UTC, shuse2 approved these changes
other than one minor comment it looks good

2023-09-07 12:00 UTC, sameersubudhi commented on src/utils/node.ts
> +const INSTALL_LISK_CORE_COMMAND = 'npm i -g lisk-core@^4.0.0-beta.5';
We'll update it to rc, when we update the SDK dependency with v6.0.0-rc.0 👍

2023-09-07 14:39 UTC, merged