Snapshot Lisk Core - Closes #49
LiskHQ/lisk-migrator pull request #61
Opened 2022-10-06 04:14 UTC by nagdahimanshu

### What was the problem?

This PR resolves #49 

### How was it solved?

- [ ] Lisk Migrator is able to observe the chain height on the node
- [ ] As soon as the chain height reaches the snapshot height (snapshot-height flag), cache the block ID and issue the command to snapshot the state on the Lisk Core node
- [ ] After the state snapshot is created successfully, observe the chain for the block at the snapshot height to be finalized
- [ ] Verify the block ID at the snapshot height is exactly the same after finalization
- [ ] Stop the Lisk Core v3 node
- [ ] Create a new DB instance to be used for the migration process using lisk-db
- [ ] After the block at snapshot height is finalized, apply the generated snapshot to the migration DB instance using lisk-db
- [ ] Start the snapshot block building process

### How was it tested?
Local

2022-10-09 15:25 UTC, sameersubudhi requested changes
Please consider the following.

2022-10-09 15:25 UTC, sameersubudhi commented on src/index.ts
> +				'Path where the state snapshot will be creating. Current directory will be considered the default if not provided.',
```suggestion
				'Path where the state snapshot will be created. When not supplied, defaults to the current directory.',
```

2022-10-09 15:25 UTC, sameersubudhi commented on src/index.ts
> +		await createSnapshot(snapshotPath);
This should also take the `liskCorePath` as input.

2022-10-09 15:25 UTC, sameersubudhi commented on src/index.ts
> +			this.error('BlockID doesnt match with the finalized blockID');
```suggestion
			this.error('Snapshotted blockID doesn't match with the finalized blockID.');
```

2022-10-09 15:25 UTC, sameersubudhi commented on src/index.ts
> +		// TODO: Stop lisk core automatically if stop command is available from SDK
```suggestion
		// TODO: Stop lisk core automatically when the application management is implemented
```

2022-10-09 15:25 UTC, sameersubudhi commented on src/utils/chain.ts
> +let blockID: string;
Please rename the variable to be more intuitive.
```suggestion
let blockIDAtSnapshotHeight: string;
```

2022-10-09 15:25 UTC, sameersubudhi commented on src/utils/chain.ts
>  	const client = await getClient(liskCorePath);
Please consider renaming this method to `getAPIClient`. Also, please consider creating two separate methods: `getCurrentFinalizedHeight` and `getCurrentChainHeight`.
```suggestion
	const client = await getAPIClient(liskCorePath);
```

2022-10-09 15:25 UTC, sameersubudhi commented on src/utils/chain.ts
> +export const getBlockIDAtSnapshotHeight = (): string => blockID;
A setter should not return any value. 
```suggestion
export const setBlockIDAtSnapshotHeight = async (
	liskCorePath: string,
	height: number,
): void => {
	const client = await getClient(liskCorePath);
	const result = await client.block.getByHeight(height);
	blockIDAtSnapshotHeight = result.header.id.toString('hex');
};

export const getBlockIDAtSnapshotHeight = (): string => blockIDAtSnapshotHeight;
```

2022-10-09 15:25 UTC, sameersubudhi commented on src/utils/chain.ts
> +export const getBlockIDAtSnapshotHeightFinalized = async (
This method can be named generic.
```suggestion
export const getBlockIDAtHeight = async (
```

2022-10-09 19:27 UTC, sameersubudhi commented on src/client.ts
> +export const getAPIClient = async (liskCorePath: string): Promise<any> => {
```suggestion
export const getAPIClient = async (liskCorePath: string): Promise<APIClient> => {
```

2022-10-09 19:32 UTC, sameersubudhi requested changes

2022-10-09 19:32 UTC, sameersubudhi commented on src/utils/chain.ts
> +	return blockIDAtSnapshotHeightFinalized;
```suggestion
	const blockID = result.header.id.toString('hex');
	return blockID;
```

2022-10-10 21:50 UTC, sameersubudhi requested changes

2022-10-10 21:50 UTC, sameersubudhi commented on src/utils/chain.ts
> +import { getAPIClient } from '../client';
Please run `npm i -S @liskhq/lisk-chain` and make the following changes to replace `Record<string, any>` with `Record<string, unknown>` below.

```suggestion
import { Block, BlockHeader } from '@liskhq/lisk-chain';
import { getAPIClient } from '../client';
```

2022-10-10 21:50 UTC, sameersubudhi commented on src/utils/chain.ts
> +	blockIDAtSnapshotHeight = result.header.id.toString('hex');
```suggestion
	const result = await client.block.getByHeight(height) as Record<string, Block>;
	const blockHeader = result.header as unknown as BlockHeader;
	blockIDAtSnapshotHeight = blockHeader.id.toString('hex');
```

2022-10-10 21:50 UTC, sameersubudhi commented on src/utils/chain.ts
> +	const blockID = result.header.id.toString('hex');
```suggestion
	const result: Record<string, unknown> = await client.block.getByHeight(height);
	const blockHeader = result.header as unknown as BlockHeader;
	const blockID = blockHeader.id.toString('hex');
```

2022-10-11 09:40 UTC, nagdahimanshu commented on src/types.ts
> +export interface Transaction {
Yes, i used from SDK but forget to remove. Thanks

2022-10-12 08:03 UTC, ManuGowda approved these changes
👍🏼

2022-10-12 08:04 UTC, merged