Update Interoperability module asset creation
LiskHQ/lisk-migrator pull request #89
Opened 2023-03-01 08:00 UTC by nagdahimanshu

### What was the problem?

This PR resolves #84 

### How was it solved?

- [ ] Update Interoperability module asset creation  
  - [ ] Update `addInteropModuleEntry` method
  - [ ] Update type and schema
  - [ ] Update unit test

### How was it tested?
Local

2023-04-17 16:13 UTC, sameersubudhi requested changes

2023-04-17 16:13 UTC, sameersubudhi commented on src/types.ts
> +export interface TerminatedOutboxAccounts {
```suggestion
export interface TerminatedOutboxAccount {
```

2023-04-17 16:13 UTC, sameersubudhi commented on src/types.ts
> +	terminatedOutboxAccounts: TerminatedOutboxAccounts[];
```suggestion
	chainInfos: ChainInfo[];
	terminatedStateAccounts: TerminatedStateAccount[];
	terminatedOutboxAccounts: TerminatedOutboxAccount[];
```

2023-04-17 16:13 UTC, sameersubudhi commented on src/assets/interoperability.ts
> -	EMPTY_BYTES,
Please check and remove any unnecessary constants from the file, if they're not being used elsewhere.

2023-04-17 16:13 UTC, sameersubudhi commented on src/types.ts
Please adjust the interface names wherever applicable.

2023-04-18 09:15 UTC, sergeyshemyakov approved these changes
The Interoperability genesis logic is correct.

2023-04-18 10:09 UTC, sameersubudhi approved these changes
LGTM 👍

2023-04-18 10:10 UTC, merged